; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Skelbiu API"
#define MyAppVersion "1.1"
#define MyAppPublisher "Adomas Lukoševičius"
#define MyAppURL "https://github.com/adomascx/Skelbiu_API/"
#define MyAppExeName "skelbiu-api.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0C17B1CB-195E-483C-A180-A82144DFA74D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\Skelbiu_API
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=build
OutputBaseFilename=Skelbiu_API_setup
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "build\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
const
  DefaultUseConcurrency = 'false';
  DefaultRateLimit = '1500';
  DefaultUseCaching = 'false';

var
  EnvPage: TWizardPage;
  ModifyEnvCheckBox: TNewCheckBox;
  UseConcurrencyLabel: TNewStaticText;
  UseConcurrencyEdit: TNewEdit;
  RateLimitLabel: TNewStaticText;
  RateLimitEdit: TNewEdit;
  UseCachingLabel: TNewStaticText;
  UseCachingEdit: TNewEdit;

procedure SetEnvFieldsEnabled(Enabled: Boolean);
begin
  UseConcurrencyLabel.Enabled := Enabled;
  UseConcurrencyEdit.Enabled := Enabled;
  RateLimitLabel.Enabled := Enabled;
  RateLimitEdit.Enabled := Enabled;
  UseCachingLabel.Enabled := Enabled;
  UseCachingEdit.Enabled := Enabled;
end;

procedure ModifyEnvCheckBoxClick(Sender: TObject);
begin
  SetEnvFieldsEnabled(ModifyEnvCheckBox.Checked);
end;

function EnvValue(Edit: TNewEdit; DefaultValue: String): String;
begin
  if ModifyEnvCheckBox.Checked then
    Result := Edit.Text
  else
    Result := DefaultValue;
end;

procedure InitializeWizard;
begin
  EnvPage := CreateCustomPage(wpSelectTasks,
    'Environment variables',
    'Choose whether to modify the API .env values.');

  ModifyEnvCheckBox := TNewCheckBox.Create(EnvPage);
  ModifyEnvCheckBox.Parent := EnvPage.Surface;
  ModifyEnvCheckBox.Left := 0;
  ModifyEnvCheckBox.Top := 0;
  ModifyEnvCheckBox.Width := EnvPage.SurfaceWidth;
  ModifyEnvCheckBox.Caption := 'Modify environment variables now';
  ModifyEnvCheckBox.Checked := False;
  ModifyEnvCheckBox.OnClick := @ModifyEnvCheckBoxClick;

  UseConcurrencyLabel := TNewStaticText.Create(EnvPage);
  UseConcurrencyLabel.Parent := EnvPage.Surface;
  UseConcurrencyLabel.Left := 0;
  UseConcurrencyLabel.Top := ScaleY(36);
  UseConcurrencyLabel.Width := EnvPage.SurfaceWidth;
  UseConcurrencyLabel.Caption := 'USE_CONCURRENCY - run scraping in async. Can result in blocked requests.';

  UseConcurrencyEdit := TNewEdit.Create(EnvPage);
  UseConcurrencyEdit.Parent := EnvPage.Surface;
  UseConcurrencyEdit.Left := 0;
  UseConcurrencyEdit.Top := UseConcurrencyLabel.Top + ScaleY(18);
  UseConcurrencyEdit.Width := EnvPage.SurfaceWidth;
  UseConcurrencyEdit.Text := DefaultUseConcurrency;

  RateLimitLabel := TNewStaticText.Create(EnvPage);
  RateLimitLabel.Parent := EnvPage.Surface;
  RateLimitLabel.Left := 0;
  RateLimitLabel.Top := UseConcurrencyEdit.Top + ScaleY(34);
  RateLimitLabel.Width := EnvPage.SurfaceWidth;
  RateLimitLabel.Caption := 'RATE_LIMIT - delay in ms between requests';

  RateLimitEdit := TNewEdit.Create(EnvPage);
  RateLimitEdit.Parent := EnvPage.Surface;
  RateLimitEdit.Left := 0;
  RateLimitEdit.Top := RateLimitLabel.Top + ScaleY(18);
  RateLimitEdit.Width := EnvPage.SurfaceWidth;
  RateLimitEdit.Text := DefaultRateLimit;

  UseCachingLabel := TNewStaticText.Create(EnvPage);
  UseCachingLabel.Parent := EnvPage.Surface;
  UseCachingLabel.Left := 0;
  UseCachingLabel.Top := RateLimitEdit.Top + ScaleY(34);
  UseCachingLabel.Width := EnvPage.SurfaceWidth;
  UseCachingLabel.Caption := 'USE_CACHING - cache backend results';

  UseCachingEdit := TNewEdit.Create(EnvPage);
  UseCachingEdit.Parent := EnvPage.Surface;
  UseCachingEdit.Left := 0;
  UseCachingEdit.Top := UseCachingLabel.Top + ScaleY(18);
  UseCachingEdit.Width := EnvPage.SurfaceWidth;
  UseCachingEdit.Text := DefaultUseCaching;

  SetEnvFieldsEnabled(False);
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  EnvText: String;
begin
  if CurStep = ssPostInstall then
  begin
    EnvText :=
      '# Whether to run scraping in async. Can result in blocked requests.' + #13#10 +
      'USE_CONCURRENCY=' + EnvValue(UseConcurrencyEdit, DefaultUseConcurrency) + #13#10#13#10 +
      '# Delay in ms between sending requests.' + #13#10 +
      'RATE_LIMIT=' + EnvValue(RateLimitEdit, DefaultRateLimit) + #13#10#13#10 +
      '# Whether to cache results in the backend. Violates GDPR. Do not use.' + #13#10 +
      'USE_CACHING=' + EnvValue(UseCachingEdit, DefaultUseCaching) + #13#10;

    SaveStringToFile(ExpandConstant('{app}\.env'), EnvText, False);
  end;
end;
